// <auto-generated />
using System;
using FuelPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelPro.Data.Migrations
{
    [DbContext(typeof(FuelProDbContext))]
    [Migration("20260619105954_AddDsmPhase1Tables")]
    partial class AddDsmPhase1Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsDailySummary", b =>
                {
                    b.Property<int>("AgsDailySummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DayTotalHsdLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("DayTotalMsIILitres")
                        .HasColumnType("REAL");

                    b.Property<double>("DayTotalMsILitres")
                        .HasColumnType("REAL");

                    b.Property<double>("HsdDayClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("HsdDayOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MsIDayClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIDayOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIIDayClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIIDayOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<string>("NozzleDaySalesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<bool>("ShiftAImported")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShiftBImported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShiftBreakdownJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<bool>("ShiftCImported")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AgsDailySummaryId");

                    b.HasIndex("SummaryDate")
                        .IsUnique();

                    b.ToTable("AgsDailySummaries");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsNozzleReading", b =>
                {
                    b.Property<int>("AgsNozzleReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgsShiftImportId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClosingReading")
                        .HasColumnType("REAL");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("NetSaleLitres")
                        .HasColumnType("REAL");

                    b.Property<int>("NozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OpeningReading")
                        .HasColumnType("REAL");

                    b.Property<int>("PumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SaleLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("TestingDeduction")
                        .HasColumnType("REAL");

                    b.HasKey("AgsNozzleReadingId");

                    b.HasIndex("AgsShiftImportId");

                    b.ToTable("AgsNozzleReadings");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsShiftImport", b =>
                {
                    b.Property<int>("AgsShiftImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("HsdClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("HsdOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<double>("MsIClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIIClosingStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIIOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MsIOpeningStock")
                        .HasColumnType("REAL");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPeriodFrom")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPeriodTo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalHsdLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalMsIILitres")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalMsILitres")
                        .HasColumnType("REAL");

                    b.HasKey("AgsShiftImportId");

                    b.HasIndex("ImportDate", "ShiftType", "IsActive");

                    b.ToTable("AgsShiftImports");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsTankStock", b =>
                {
                    b.Property<int>("AgsTankStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgsShiftImportId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClosingDipMM")
                        .HasColumnType("REAL");

                    b.Property<double>("ClosingStockLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelDispensedLitres")
                        .HasColumnType("REAL");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("OpeningDipMM")
                        .HasColumnType("REAL");

                    b.Property<double>("OpeningStockLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("ReceiptLitres")
                        .HasColumnType("REAL");

                    b.Property<int>("TankNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgsTankStockId");

                    b.HasIndex("AgsShiftImportId");

                    b.ToTable("AgsTankStocks");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AppMeta", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppMeta");
                });

            modelBuilder.Entity("FuelPro.Core.Models.CashDenomination", b =>
                {
                    b.Property<int>("CashDenomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CashType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom200")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom50")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denom500")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("CashDenomId");

                    b.HasIndex("DsmEntryId", "CashType")
                        .IsUnique();

                    b.ToTable("CashDenominations");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Creditor", b =>
                {
                    b.Property<int>("CreditorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CreditorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Creditors");
                });

            modelBuilder.Entity("FuelPro.Core.Models.CreditorRepayment", b =>
                {
                    b.Property<int>("CreditorRepaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ChequeNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RepaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CreditorRepaymentId");

                    b.ToTable("CreditorRepayments");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DebitEntry", b =>
                {
                    b.Property<int>("DebitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ChequeNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DebitId");

                    b.HasIndex("DsmEntryId");

                    b.ToTable("DebitEntries");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmApprovalAudit", b =>
                {
                    b.Property<int>("DsmApprovalAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("DsmApprovalAuditId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("DsmApprovalAudits");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmAttendance", b =>
                {
                    b.Property<int>("DsmAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DsmUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DsmAttendanceId");

                    b.HasIndex("DsmUserId", "AttendanceDate", "ShiftType")
                        .IsUnique();

                    b.ToTable("DsmAttendance");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmDevice", b =>
                {
                    b.Property<int>("DsmDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DsmUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("DsmDeviceId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DsmUserId");

                    b.ToTable("DsmDevices");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmEntry", b =>
                {
                    b.Property<int>("DsmEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectedPumpId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DsmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mismatch")
                        .HasColumnType("TEXT");

                    b.Property<int>("PumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReconciledToPumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCollection")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCreditors")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalInDirect")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DsmEntryId");

                    b.HasIndex("ShiftId", "DsmName", "ReconciledToPumpId");

                    b.HasIndex("ShiftId", "PumpId", "DsmName");

                    b.ToTable("DsmEntries");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmProfile", b =>
                {
                    b.Property<int>("DsmProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("REAL");

                    b.Property<string>("DsmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DsmProfileId");

                    b.HasIndex("DsmName")
                        .IsUnique();

                    b.ToTable("DsmProfiles");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmPumpAssignment", b =>
                {
                    b.Property<int>("DsmPumpAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DsmUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PumpId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("DsmPumpAssignmentId");

                    b.HasIndex("DsmUserId");

                    b.HasIndex("PumpId", "ShiftType", "IsActive");

                    b.ToTable("DsmPumpAssignments");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmSalaryAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdvancePaid")
                        .HasColumnType("REAL");

                    b.Property<string>("DsmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OtherAdjustments")
                        .HasColumnType("REAL");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DsmSalaryAdjustments");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmUser", b =>
                {
                    b.Property<int>("DsmUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("DsmUserId");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("DsmUsers");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpenseId");

                    b.HasIndex("DsmEntryId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FuelPro.Core.Models.FuelProfitMargin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("MarginPerLitre")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FuelProfitMargins");
                });

            modelBuilder.Entity("FuelPro.Core.Models.NozzleReading", b =>
                {
                    b.Property<int>("NozzleReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<double>("ClosingReading")
                        .HasColumnType("REAL");

                    b.Property<int>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManualOpeningOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OpeningReading")
                        .HasColumnType("REAL");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<double>("SaleLitres")
                        .HasColumnType("REAL");

                    b.HasKey("NozzleReadingId");

                    b.HasIndex("DsmEntryId");

                    b.ToTable("NozzleReadings");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefDailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AddedQuantity")
                        .HasColumnType("REAL");

                    b.Property<double>("AdjustmentQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("AdjustmentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OverrideSaleRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("RemainingStock")
                        .HasColumnType("REAL");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<double>("SoldQuantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OilDefDailyLogs");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClosingStock")
                        .HasColumnType("REAL");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OpeningStock")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OilDefInventories");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OilDefPurchases");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OuterExpense", b =>
                {
                    b.Property<int>("OuterExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OuterExpenseId");

                    b.ToTable("OuterExpenses");
                });

            modelBuilder.Entity("FuelPro.Core.Models.PaymentCollection", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CashDeposit")
                        .HasColumnType("REAL");

                    b.Property<double>("CreditCardMorning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CreditCardNight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Others")
                        .HasColumnType("REAL");

                    b.Property<double>("PetroCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PhonePeCardMorning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PhonePeCardNight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PhonePeMorning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PhonePeNight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("PaymentId");

                    b.HasIndex("DsmEntryId")
                        .IsUnique();

                    b.ToTable("PaymentCollections");
                });

            modelBuilder.Entity("FuelPro.Core.Models.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultSaleRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("HsdRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(90.349999999999994);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("MsIIRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(103.81);

                    b.Property<double>("MsIRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(103.81);

                    b.Property<string>("PumpStationName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PyroSync");

                    b.HasKey("SettingId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("ShiftId");

                    b.HasIndex("ShiftDate", "ShiftType")
                        .IsUnique();

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FuelPro.Core.Models.ShiftFuelRate", b =>
                {
                    b.Property<int>("ShiftFuelRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("OverrideRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShiftNumber")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("ShiftFuelRateId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("ShiftDate", "ShiftNumber", "FuelType")
                        .IsUnique();

                    b.ToTable("ShiftFuelRates");
                });

            modelBuilder.Entity("FuelPro.Core.Models.ShiftOtherCash", b =>
                {
                    b.Property<int>("ShiftOtherCashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShiftNumber")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("ShiftOtherCashId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("ShiftDate", "ShiftNumber");

                    b.ToTable("ShiftOtherCash");
                });

            modelBuilder.Entity("FuelPro.Core.Models.SyncChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordGuid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncChangeLogs");
                });

            modelBuilder.Entity("FuelPro.Core.Models.SyncIdMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableName", "RemoteGuid")
                        .IsUnique();

                    b.ToTable("SyncIdMappings");
                });

            modelBuilder.Entity("FuelPro.Core.Models.TestingEntry", b =>
                {
                    b.Property<int>("TestingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("DsmEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Litres")
                        .HasColumnType("REAL");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.HasKey("TestingId");

                    b.HasIndex("DsmEntryId");

                    b.ToTable("TestingEntries");
                });

            modelBuilder.Entity("FuelPro.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Operator");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsNozzleReading", b =>
                {
                    b.HasOne("FuelPro.Core.Models.AGS.AgsShiftImport", "AgsShiftImport")
                        .WithMany("NozzleReadings")
                        .HasForeignKey("AgsShiftImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgsShiftImport");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsTankStock", b =>
                {
                    b.HasOne("FuelPro.Core.Models.AGS.AgsShiftImport", "AgsShiftImport")
                        .WithMany("TankStocks")
                        .HasForeignKey("AgsShiftImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgsShiftImport");
                });

            modelBuilder.Entity("FuelPro.Core.Models.CashDenomination", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithMany("CashDenominations")
                        .HasForeignKey("DsmEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmEntry");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DebitEntry", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithMany("DebitEntries")
                        .HasForeignKey("DsmEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmEntry");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmAttendance", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmUser", "DsmUser")
                        .WithMany()
                        .HasForeignKey("DsmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmUser");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmDevice", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmUser", "DsmUser")
                        .WithMany()
                        .HasForeignKey("DsmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmUser");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmEntry", b =>
                {
                    b.HasOne("FuelPro.Core.Models.Shift", "Shift")
                        .WithMany("DsmEntries")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmPumpAssignment", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmUser", "DsmUser")
                        .WithMany()
                        .HasForeignKey("DsmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmUser");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Expense", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithMany("Expenses")
                        .HasForeignKey("DsmEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FuelPro.Core.Models.Shift", "Shift")
                        .WithMany("Expenses")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DsmEntry");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelPro.Core.Models.NozzleReading", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithMany("NozzleReadings")
                        .HasForeignKey("DsmEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmEntry");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefDailyLog", b =>
                {
                    b.HasOne("FuelPro.Core.Models.ProductMaster", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefInventory", b =>
                {
                    b.HasOne("FuelPro.Core.Models.ProductMaster", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FuelPro.Core.Models.OilDefPurchase", b =>
                {
                    b.HasOne("FuelPro.Core.Models.ProductMaster", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FuelPro.Core.Models.PaymentCollection", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithOne("PaymentCollection")
                        .HasForeignKey("FuelPro.Core.Models.PaymentCollection", "DsmEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmEntry");
                });

            modelBuilder.Entity("FuelPro.Core.Models.ShiftFuelRate", b =>
                {
                    b.HasOne("FuelPro.Core.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelPro.Core.Models.ShiftOtherCash", b =>
                {
                    b.HasOne("FuelPro.Core.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelPro.Core.Models.TestingEntry", b =>
                {
                    b.HasOne("FuelPro.Core.Models.DsmEntry", "DsmEntry")
                        .WithMany("TestingEntries")
                        .HasForeignKey("DsmEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsmEntry");
                });

            modelBuilder.Entity("FuelPro.Core.Models.AGS.AgsShiftImport", b =>
                {
                    b.Navigation("NozzleReadings");

                    b.Navigation("TankStocks");
                });

            modelBuilder.Entity("FuelPro.Core.Models.DsmEntry", b =>
                {
                    b.Navigation("CashDenominations");

                    b.Navigation("DebitEntries");

                    b.Navigation("Expenses");

                    b.Navigation("NozzleReadings");

                    b.Navigation("PaymentCollection");

                    b.Navigation("TestingEntries");
                });

            modelBuilder.Entity("FuelPro.Core.Models.Shift", b =>
                {
                    b.Navigation("DsmEntries");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
