<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateMSBuildEditorConfig>false</GenerateMSBuildEditorConfig>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FuelPro.Core\FuelPro.Core.csproj" />
    <ProjectReference Include="..\FuelPro.Data\FuelPro.Data.csproj" />
  </ItemGroup>

</Project>
