using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using FuelPro.Core.Models;
using FuelPro.Core.Services;
using FuelPro.Data;
using FuelPro.Data.Repositories;

namespace FuelPro.Maintenance;

class Program
{
    static async Task<int> Main(string[] args)
    {
        // Force production path resolution for LocalCredentialFileService
        Environment.SetEnvironmentVariable("FUELPRO_ENV", "PRODUCTION");

        if (args.Length == 0 || args[0] != "reset-dev")
        {
            Console.WriteLine("FuelPro Maintenance Utility");
            Console.WriteLine("===========================");
            Console.WriteLine("Usage: dotnet run --project src/FuelPro.Maintenance -- reset-dev [--pin <override-pin>] [--force]");
            return 1;
        }

        // Parse optional arguments
        string? pinOverride = null;
        bool force = false;

        for (int i = 1; i < args.Length; i++)
        {
            if (args[i] == "--pin" && i + 1 < args.Length)
            {
                pinOverride = args[++i];
            }
            else if (args[i] == "--force")
            {
                force = true;
            }
        }

        // Resolve paths
        var appDataFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FuelPro");
        var dbPath = Path.Combine(appDataFolder, "fuelPro.db");
        var backupPath = Path.Combine(appDataFolder, "fuelPro.db.bak");

        Console.WriteLine($"Database Path: {dbPath}");
        if (!File.Exists(dbPath))
        {
            Console.Error.WriteLine($"[ERROR] SQLite database file not found at: {dbPath}");
            return 1;
        }

        // Accidental Production Execution Prevention
        if (!force)
        {
            Console.WriteLine();
            Console.WriteLine("WARNING:");
            Console.WriteLine("This will modify Developer credentials in the active SQLite database.");
            Console.WriteLine($"Database: {dbPath}");
            Console.Write("Type YES to continue: ");
            var response = Console.ReadLine();
            if (response != "YES")
            {
                Console.WriteLine("Operation cancelled by user.");
                return 0;
            }
        }

        // 1. Create database backup
        Console.WriteLine("\n[1/4] Creating database backup...");
        bool backupSuccess = false;
        string backupLogMsg = "";
        try
        {
            File.Copy(dbPath, backupPath, overwrite: true);
            backupSuccess = true;
            backupLogMsg = $"Backup created successfully at: {backupPath}";
            Console.WriteLine($"[SUCCESS] {backupLogMsg}");
        }
        catch (Exception ex)
        {
            backupLogMsg = $"Backup creation failed: {ex.Message}";
            Console.Error.WriteLine($"[ERROR] {backupLogMsg}");
            return 1;
        }

        // 2. Open DbContext and verify Developer user exists
        Console.WriteLine("[2/4] Connecting to database and verifying Developer account...");
        var options = new DbContextOptionsBuilder<FuelProDbContext>()
            .UseSqlite($"Data Source={dbPath};Busy Timeout=5000")
            .Options;

        using var context = new FuelProDbContext(options);
        var devUser = await context.Users.FirstOrDefaultAsync(u => u.Username == "Developer" || u.Role == "Developer");
        if (devUser == null)
        {
            Console.Error.WriteLine("[ERROR] Developer account record not found in database!");
            return 1;
        }
        Console.WriteLine($"[SUCCESS] Developer account found (ID: {devUser.UserId}, Role: {devUser.Role})");

        // 3. Determine PIN and update hash
        string targetPin = pinOverride;
        bool isAutoGenerated = false;
        if (string.IsNullOrEmpty(targetPin))
        {
            targetPin = Random.Shared.Next(100000, 999999).ToString("D6");
            isAutoGenerated = true;
            Console.WriteLine($"[INFO] Generating new random secure 6-digit PIN: {targetPin}");
        }
        else
        {
            Console.WriteLine($"[INFO] Using manually supplied PIN override: {targetPin}");
        }

        Console.WriteLine("[3/4] Updating credentials in database and writing credential file...");
        try
        {
            // Update DB hash
            devUser.PinHash = BCrypt.Net.BCrypt.HashPassword(targetPin);
            await context.SaveChangesAsync();
            Console.WriteLine("[SUCCESS] Developer PIN hash updated in SQLite database.");

            // Update dev_credential.txt file
            var credentialService = new LocalCredentialFileService(appDataFolder);
            await credentialService.WriteCredentialAsync("Developer", targetPin);
            Console.WriteLine($"[SUCCESS] Credential file written to: {credentialService.GetCredentialFilePath()}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ERROR] Failed to save credentials: {ex.Message}");
            return 1;
        }

        // 4. Verify login using AuthService
        Console.WriteLine("[4/4] Verifying authentication with new credentials...");
        bool loginSuccess = false;
        try
        {
            var userRepo = new UserRepository(context);
            var authService = new AuthService(userRepo);
            var loginResult = await authService.LoginAsync("Developer", targetPin);
            loginSuccess = loginResult.Success;

            if (loginSuccess)
            {
                Console.WriteLine("[SUCCESS] Authentication verification succeeded!");
            }
            else
            {
                Console.Error.WriteLine("[ERROR] Authentication verification failed: invalid credentials returned.");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ERROR] Verification threw exception: {ex.Message}");
        }

        // Generate Audit Logging Report
        var workspaceRoot = FindWorkspaceRoot();
        var reportPath = Path.Combine(workspaceRoot, "developer_reset_verification_report.md");
        
        var reportContent = $@"# Developer Credential Reset & Verification Report

This report documents the execution and verification details of the Developer credential reset.

## Audit Log
- **Timestamp**: {DateTime.Now:yyyy-MM-dd HH:mm:ss} (Local Time)
- **Machine Name**: {Environment.MachineName}
- **Windows Username**: {Environment.UserName}
- **Database Path**: `{dbPath}`
- **Backup File Path**: `{backupPath}`
- **Backup Creation Log**: {backupLogMsg}
- **PIN Source**: {(isAutoGenerated ? "Auto-generated" : "Manually supplied override")}
- **Active PIN**: `{targetPin}`
- **Authentication Verification**: {(loginSuccess ? "PASSED (Login Successful)" : "FAILED")}

---

## Verification Summary
1. **Database Backup**: **{(backupSuccess ? "COMPLETED" : "FAILED")}**
2. **Developer Record Found**: **YES** (Username: `{devUser.Username}`, Role: `{devUser.Role}`)
3. **Password Hash Updated**: **YES**
4. **Credential File Re-written**: **YES** (`{Path.Combine(appDataFolder, "dev_credential.txt")}`)
5. **AuthService Login Test**: **{(loginSuccess ? "SUCCESS" : "FAIL")}**

## Rollback Path
If you need to roll back this reset, restore the backup from:
`{backupPath}` to `{dbPath}`.
";

        await File.WriteAllTextAsync(reportPath, reportContent);
        Console.WriteLine($"\n[SUCCESS] Audit verification report written to: {reportPath}");

        return loginSuccess ? 0 : 1;
    }

    private static string FindWorkspaceRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            if (dir.GetFiles("FuelPro.sln").Length > 0)
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return Directory.GetCurrentDirectory();
    }
}
