using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using FuelPro.Core.Models;
using FuelPro.Core.DTOs;
using FuelPro.Core.Services;
using FuelPro.Data;
using FuelPro.Data.Repositories;

namespace FuelPro.Maintenance;

class Program
{
    static async Task<int> Main(string[] args)
    {
        // Force production path resolution for LocalCredentialFileService
        Environment.SetEnvironmentVariable("FUELPRO_ENV", "PRODUCTION");

        if (args.Length == 0)
        {
            Console.WriteLine("FuelPro Maintenance Utility");
            Console.WriteLine("===========================");
            Console.WriteLine("Usage: dotnet run --project src/FuelPro.Maintenance -- [reset-dev | analyze-nozzles | restore-nozzles]");
            return 1;
        }

        if (args[0] == "analyze-nozzles" || args[0] == "restore-nozzles")
        {
            return await RunNozzleDiagnosticsAsync(args);
        }

        // Parse optional arguments
        string? pinOverride = null;
        bool force = false;

        for (int i = 1; i < args.Length; i++)
        {
            if (args[i] == "--pin" && i + 1 < args.Length)
            {
                pinOverride = args[++i];
            }
            else if (args[i] == "--force")
            {
                force = true;
            }
        }

        // Resolve paths
        var appDataFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FuelPro");
        var dbPath = Path.Combine(appDataFolder, "fuelPro.db");
        var backupPath = Path.Combine(appDataFolder, "fuelPro.db.bak");

        Console.WriteLine($"Database Path: {dbPath}");
        if (!File.Exists(dbPath))
        {
            Console.Error.WriteLine($"[ERROR] SQLite database file not found at: {dbPath}");
            return 1;
        }

        // Accidental Production Execution Prevention
        if (!force)
        {
            Console.WriteLine();
            Console.WriteLine("WARNING:");
            Console.WriteLine("This will modify Developer credentials in the active SQLite database.");
            Console.WriteLine($"Database: {dbPath}");
            Console.Write("Type YES to continue: ");
            var response = Console.ReadLine();
            if (response != "YES")
            {
                Console.WriteLine("Operation cancelled by user.");
                return 0;
            }
        }

        // 1. Create database backup
        Console.WriteLine("\n[1/4] Creating database backup...");
        bool backupSuccess = false;
        string backupLogMsg = "";
        try
        {
            File.Copy(dbPath, backupPath, overwrite: true);
            backupSuccess = true;
            backupLogMsg = $"Backup created successfully at: {backupPath}";
            Console.WriteLine($"[SUCCESS] {backupLogMsg}");
        }
        catch (Exception ex)
        {
            backupLogMsg = $"Backup creation failed: {ex.Message}";
            Console.Error.WriteLine($"[ERROR] {backupLogMsg}");
            return 1;
        }

        // 2. Open DbContext and verify Developer user exists
        Console.WriteLine("[2/4] Connecting to database and verifying Developer account...");
        var options = new DbContextOptionsBuilder<FuelProDbContext>()
            .UseSqlite($"Data Source={dbPath};Default Timeout=5")
            .Options;

        using var context = new FuelProDbContext(options);
        var devUser = await context.Users.FirstOrDefaultAsync(u => u.Username == "Developer" || u.Role == "Developer");
        if (devUser == null)
        {
            Console.Error.WriteLine("[ERROR] Developer account record not found in database!");
            return 1;
        }
        Console.WriteLine($"[SUCCESS] Developer account found (ID: {devUser.UserId}, Role: {devUser.Role})");

        // 3. Determine PIN and update hash
        string targetPin = pinOverride;
        bool isAutoGenerated = false;
        if (string.IsNullOrEmpty(targetPin))
        {
            targetPin = Random.Shared.Next(100000, 999999).ToString("D6");
            isAutoGenerated = true;
            Console.WriteLine($"[INFO] Generating new random secure 6-digit PIN: {targetPin}");
        }
        else
        {
            Console.WriteLine($"[INFO] Using manually supplied PIN override: {targetPin}");
        }

        Console.WriteLine("[3/4] Updating credentials in database and writing credential file...");
        try
        {
            // Update DB hash
            devUser.PinHash = BCrypt.Net.BCrypt.HashPassword(targetPin);
            await context.SaveChangesAsync();
            Console.WriteLine("[SUCCESS] Developer PIN hash updated in SQLite database.");

            // Update dev_credential.txt file
            var credentialService = new LocalCredentialFileService(appDataFolder);
            await credentialService.WriteCredentialAsync("Developer", targetPin);
            Console.WriteLine($"[SUCCESS] Credential file written to: {credentialService.GetCredentialFilePath()}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ERROR] Failed to save credentials: {ex.Message}");
            return 1;
        }

        // 4. Verify login using AuthService
        Console.WriteLine("[4/4] Verifying authentication with new credentials...");
        bool loginSuccess = false;
        try
        {
            var userRepo = new UserRepository(context);
            var authService = new AuthService(userRepo);
            var loginResult = await authService.LoginAsync("Developer", targetPin);
            loginSuccess = loginResult.Success;

            if (loginSuccess)
            {
                Console.WriteLine("[SUCCESS] Authentication verification succeeded!");
            }
            else
            {
                Console.Error.WriteLine("[ERROR] Authentication verification failed: invalid credentials returned.");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ERROR] Verification threw exception: {ex.Message}");
        }

        // Generate Audit Logging Report
        var workspaceRoot = FindWorkspaceRoot();
        var reportPath = Path.Combine(workspaceRoot, "developer_reset_verification_report.md");
        
        var reportContent = $@"# Developer Credential Reset & Verification Report

This report documents the execution and verification details of the Developer credential reset.

## Audit Log
- **Timestamp**: {DateTime.Now:yyyy-MM-dd HH:mm:ss} (Local Time)
- **Machine Name**: {Environment.MachineName}
- **Windows Username**: {Environment.UserName}
- **Database Path**: `{dbPath}`
- **Backup File Path**: `{backupPath}`
- **Backup Creation Log**: {backupLogMsg}
- **PIN Source**: {(isAutoGenerated ? "Auto-generated" : "Manually supplied override")}
- **Active PIN**: `{targetPin}`
- **Authentication Verification**: {(loginSuccess ? "PASSED (Login Successful)" : "FAILED")}

---

## Verification Summary
1. **Database Backup**: **{(backupSuccess ? "COMPLETED" : "FAILED")}**
2. **Developer Record Found**: **YES** (Username: `{devUser.Username}`, Role: `{devUser.Role}`)
3. **Password Hash Updated**: **YES**
4. **Credential File Re-written**: **YES** (`{Path.Combine(appDataFolder, "dev_credential.txt")}`)
5. **AuthService Login Test**: **{(loginSuccess ? "SUCCESS" : "FAIL")}**

## Rollback Path
If you need to roll back this reset, restore the backup from:
`{backupPath}` to `{dbPath}`.
";

        await File.WriteAllTextAsync(reportPath, reportContent);
        Console.WriteLine($"\n[SUCCESS] Audit verification report written to: {reportPath}");

        return loginSuccess ? 0 : 1;
    }

    private static async Task<int> RunNozzleDiagnosticsAsync(string[] args)
    {
        var appDataFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "FuelPro");
        var dbPath = Path.Combine(appDataFolder, "fuelPro.db");
        var backupPath = Path.Combine(appDataFolder, $"fuelPro_pre_nozzle_restore_{DateTime.Now:yyyyMMddHHmmss}.db.bak");

        Console.WriteLine($"[MAINTENANCE] Target SQLite DB: {dbPath}");
        if (!File.Exists(dbPath))
        {
            Console.Error.WriteLine("[ERROR] Database not found.");
            return 1;
        }

        bool isRestore = args.Length > 0 && args[0] == "restore-nozzles";

        if (isRestore)
        {
            Console.WriteLine($"[BACKUP] Creating database backup at: {backupPath}");
            File.Copy(dbPath, backupPath, overwrite: true);
        }

        var options = new DbContextOptionsBuilder<FuelProDbContext>()
            .UseSqlite($"Data Source={dbPath}")
            .Options;

        using var context = new FuelProDbContext(options);

        var allEntries = await context.DsmEntries
            .Include(e => e.Shift)
            .Include(e => e.NozzleReadings)
            .Include(e => e.PaymentCollection)
            .Include(e => e.CashDenominations)
            .Include(e => e.DebitEntries)
            .Include(e => e.Expenses)
            .Include(e => e.TestingEntries)
            .Include(e => e.KhandharePetroleumEntries)
            .OrderBy(e => e.Shift!.ShiftDate)
            .ThenBy(e => e.Shift!.ShiftType)
            .ThenBy(e => e.PumpId)
            .ToListAsync();

        // Load mappings
        var dsmMappings = await context.SyncIdMappings
            .Where(m => m.TableName == "DsmEntries")
            .ToDictionaryAsync(m => m.RemoteGuid, m => m.LocalId);

        var localDsmToRemoteGuid = await context.SyncIdMappings
            .Where(m => m.TableName == "DsmEntries")
            .ToDictionaryAsync(m => m.LocalId, m => m.RemoteGuid);

        Console.WriteLine($"Total DsmEntries mapped to RemoteGuids: {dsmMappings.Count}");

        // Fetch ALL NozzleReadings from Supabase
        using var http = new System.Net.Http.HttpClient();
        string supUrl = "https://rvcibryprvjbzrtwqktk.supabase.co/rest/v1";
        string supKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2Y2licnlwcnZqYnpydHdxa3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMTIxMTcsImV4cCI6MjA5Njg4ODExN30.vMTA97993upfnOCs5ja-kxIhDSHbcx1gEQ6itNm5BBk";
        http.DefaultRequestHeaders.Add("apikey", supKey);
        http.DefaultRequestHeaders.Add("Authorization", $"Bearer {supKey}");

        Console.WriteLine("\n[SUPABASE] Fetching all NozzleReadings from cloud...");
        var allCloudReadings = new List<System.Text.Json.JsonElement>();
        int offset = 0;
        int pageSize = 1000;
        while (true)
        {
            var res = await http.GetStringAsync($"{supUrl}/NozzleReadings?select=*&limit={pageSize}&offset={offset}");
            using var doc = System.Text.Json.JsonDocument.Parse(res);
            var arr = doc.RootElement.EnumerateArray().ToList();
            if (arr.Count == 0) break;
            allCloudReadings.AddRange(arr.Select(x => x.Clone()));
            offset += arr.Count;
            if (arr.Count < pageSize) break;
        }

        Console.WriteLine($"Fetched {allCloudReadings.Count} total NozzleReadings from Supabase.");

        // Analyze match
        int matchCount = 0;
        int missingInLocalCount = 0;
        var toInsert = new List<NozzleReading>();
        var mappingsToInsert = new List<SyncIdMapping>();

        var existingLocalNozzleReadings = await context.NozzleReadings.ToListAsync();
        var localNozzleLookup = new HashSet<string>(existingLocalNozzleReadings.Select(n => $"{n.DsmEntryId}_{n.NozzleNumber}"));
        var localNozzleMappings = new HashSet<string>((await context.SyncIdMappings.Where(m => m.TableName == "NozzleReadings").Select(m => m.RemoteGuid).ToListAsync()));

        var localEntryIds = new HashSet<int>(allEntries.Select(e => e.DsmEntryId));

        foreach (var nr in allCloudReadings)
        {
            string? parentGuid = null;
            if (nr.TryGetProperty("DsmEntryId", out var dsmProp) && dsmProp.ValueKind != System.Text.Json.JsonValueKind.Null)
            {
                parentGuid = dsmProp.GetString();
            }

            int? targetLocalDsmId = null;
            if (!string.IsNullOrEmpty(parentGuid))
            {
                if (dsmMappings.TryGetValue(parentGuid, out var mappedLocalId))
                {
                    targetLocalDsmId = mappedLocalId;
                }
                else if (int.TryParse(parentGuid, out var rawIntId) && localEntryIds.Contains(rawIntId))
                {
                    targetLocalDsmId = rawIntId;
                }
            }

            if (!targetLocalDsmId.HasValue || !localEntryIds.Contains(targetLocalDsmId.Value)) continue;
            matchCount++;

            int nozzleNum = nr.GetProperty("NozzleNumber").GetInt32();
            string key = $"{targetLocalDsmId.Value}_{nozzleNum}";

            if (!localNozzleLookup.Contains(key))
            {
                missingInLocalCount++;

                string fuelType = nr.TryGetProperty("FuelType", out var ft) ? ft.GetString() ?? "Petrol" : "Petrol";
                double open = nr.TryGetProperty("OpeningReading", out var op) ? op.GetDouble() : 0;
                double close = nr.TryGetProperty("ClosingReading", out var cl) ? cl.GetDouble() : 0;
                double rate = nr.TryGetProperty("Rate", out var rt) ? rt.GetDouble() : 0;
                double litres = nr.TryGetProperty("SaleLitres", out var sl) ? sl.GetDouble() : (close - open);
                double amount = nr.TryGetProperty("Amount", out var am) ? am.GetDouble() : (litres * rate);
                bool isOverride = nr.TryGetProperty("IsManualOpeningOverride", out var mo) && mo.GetBoolean();
                string syncGuid = nr.TryGetProperty("SyncGuid", out var sg) ? (sg.GetString() ?? Guid.NewGuid().ToString()) : Guid.NewGuid().ToString();

                var newNr = new NozzleReading
                {
                    DsmEntryId = targetLocalDsmId.Value,
                    NozzleNumber = nozzleNum,
                    FuelType = fuelType,
                    OpeningReading = open,
                    ClosingReading = close,
                    SaleLitres = litres,
                    Rate = rate,
                    Amount = amount,
                    IsManualOpeningOverride = isOverride
                };

                toInsert.Add(newNr);

                if (!localNozzleMappings.Contains(syncGuid))
                {
                    mappingsToInsert.Add(new SyncIdMapping
                    {
                        TableName = "NozzleReadings",
                        RemoteGuid = syncGuid,
                        LocalId = 0 // will update after insertion
                    });
                }
            }
        }

        Console.WriteLine($"Cloud readings matched to local DsmEntries: {matchCount}");
        Console.WriteLine($"Readings missing locally and ready to restore: {missingInLocalCount}");

        if (isRestore && toInsert.Count > 0)
        {
            Console.WriteLine($"\n[RESTORE] Inserting {toInsert.Count} NozzleReading rows into SQLite...");
            FuelProDbContext.BypassTracking = true;
            try
            {
                await context.NozzleReadings.AddRangeAsync(toInsert);
                await context.SaveChangesAsync();

                // Update mapping LocalIds
                for (int i = 0; i < toInsert.Count && i < mappingsToInsert.Count; i++)
                {
                    mappingsToInsert[i].LocalId = toInsert[i].NozzleReadingId;
                }
                if (mappingsToInsert.Count > 0)
                {
                    await context.SyncIdMappings.AddRangeAsync(mappingsToInsert);
                    await context.SaveChangesAsync();
                }

                Console.WriteLine("[SUCCESS] Successfully inserted nozzle readings into local database!");
            }
            finally
            {
                FuelProDbContext.BypassTracking = false;
            }

            // Post-restore verification
            var refreshedEntriesWithoutNozz = await context.DsmEntries
                .CountAsync(e => !context.NozzleReadings.Any(n => n.DsmEntryId == e.DsmEntryId));
            Console.WriteLine($"\n[VERIFICATION] Remaining entries without NozzleReadings: {refreshedEntriesWithoutNozz}");
        }

        return 0;
    }

    private static string FindWorkspaceRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            if (dir.GetFiles("FuelPro.sln").Length > 0)
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return Directory.GetCurrentDirectory();
    }
}
